name: Run Python Script

on:
  schedule:
    - cron: '30 6-15 * * 1-5'  # Run every minute from 6:30 AM to 3:20 PM, Monday to Friday

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want to use

      - name: Run Python script
        run: |
          python app.py
